spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3305/AuthFlow_SecureDocs
  application:
    name: AuthFlow_SecureDocs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8084